version: '3.5'

services:
  d3-iroha:
    image: hyperledger/iroha:develop
    container_name: d3-iroha
    depends_on:
      - d3-iroha-postgres
    tty: true
    environment:
      - KEY=keys/node0
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    volumes:
      - iroha_block_store:/tmp/block_store
      - ./iroha:/opt/iroha_data

  d3-iroha-postgres:
    image: postgres:9.5
    container_name: d3-iroha-postgres
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - /var/lib/postgresql/data

  # ethereum
  d3-eth-node0:
    image: parity/parity:stable
    container_name: d3-eth-node0
    volumes:
      - ./ethereum:/eth
    command:
      --config dev
      --chain /eth/genesis.block
      --cache-size 4096
      --interface all
      --jsonrpc-interface all
      --jsonrpc-port 8545
      --jsonrpc-apis all
      --jsonrpc-cors all
      --tracing on
      --max-peers 50
      --unsafe-expose

#  d3-eth-node0:
#    build:
#      context: ./ethereum
#      dockerfile: ganache.dockerfile
#    container_name: d3-eth-node0
#    volumes:
#      - ./ethereum:/eth
#    environment:
#      - NODE=0

  grpcwebproxy:
    build:
      context: grpcwebproxy/
    container_name: d3-grpcwebproxy
    depends_on:
      - d3-iroha
    entrypoint:
    - grpcwebproxy
    - --backend_addr=d3-iroha:50051
    - --run_tls_server=false

  # bitcoin
  d3-btc-node0:
    image: kylemanna/bitcoind:latest
    container_name: d3-btc-node0
    entrypoint:
    - bitcoind
    - --rpcuser=test
    - --rpcpassword=test
    - --regtest=1
    - --server=1
    - --rpcallowip=172.0.0.0/8
    - --rpcport=8332


volumes:
  iroha_block_store:
