- block:
  # TODO: uncomment
  - name: copy custom genesis block
    copy:
      src: "{{ custom_genesis_block_path }}"
      dest: "{{ role_path }}/files/genesis.block"
    when: custom_genesis_block
    failed_when: custom_genesis_block_path is not defined

  - name: generate Iroha configs
    command: "./config_gen.sh -p{{ iroha_all_nodes | join(',', attribute='hostname') }} -o{{ config_local_dir }} -f"
    run_once: yes
    args:
      chdir: "{{ role_path }}/files"

  - name: make config dirs
    file:
      path: "{{ config_local_dir }}/{{ inventory_hostname }}/conf/{{ item.human_hostname }}"
      state: directory
    loop: "{{ iroha_nodes }}"

# TODO: uncomment
  - name: move keys
    copy:
      src: "{{ config_local_dir }}/{{ item[0].hostname }}{{ item[1] }}"
      dest: "{{ config_local_dir }}/{{ inventory_hostname }}/conf/{{ item[0].human_hostname }}"
    loop: "{{ iroha_nodes | product(['.priv', '.pub']) | list }}"

  - name: move genesis.block
    copy:
      src: "{{ config_local_dir }}/genesis.block"
      dest: "{{ config_local_dir }}/{{ inventory_hostname }}/conf/{{ item.human_hostname }}"
    loop: "{{ iroha_nodes }}"

  - name: cleanup
    file:
      path: "{{ config_local_dir }}/{{ item[0].hostname }}{{ item[1] }}"
      state: absent
    loop: "{{ iroha_nodes | product(['.priv', '.pub']) | list }}"

  - name: cleanup
    file:
      path: "{{ config_local_dir }}/genesis.block"
      state: absent
    run_once: yes
  become: no
  delegate_to: localhost
  when: generate_init_configs

- name: create deploy dir
  file:
    state: directory
    path: "{{ deploy_dir }}/conf"

- name: copy config files
  synchronize:
    src: "{{ config_local_dir }}/{{ inventory_hostname }}/conf/"
    dest: "{{ deploy_dir }}/conf/"
    recursive: yes
    checksum: yes
  when: generate_init_configs