iroha_replicas: 1
bootstrap_notary_address: 'http://d3-notary-3:20000'

bootstrap_eth_registration_host: registration-eth.s3.stg1.d3.soramitsu.co.jp
bootstrap_registration_host: registration.s3.stg1.d3.soramitsu.co.jp
bootstrap_grpcwebproxy_host: grpcwebproxy.s3.stg1.d3.soramitsu.co.jp
bootstrap_btc_registration_host: registration-btc.s3.stg1.d3.soramitsu.co.jp
bootstrap_backend_host: s3.stg1.d3.soramitsu.co.jp
bootstrap_btc_address_generation_nodeid: 3
bootstrap_btc_registration_nodeid: 3
bootstrap_eth_notary_container_name: d3-notary-3
bootstrap_eth_withdrawal_container_name: d3-withdrawal-3
